language: ruby
before_install:
  - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
  - sh ./travis_setup.sh -p "yast2-devtools"
  - rm ./travis_setup.sh
script:
  - bundle exec rubocop
  - bundle exec rake package
  - bundle exec gem install --local package/libyui-rake*.gem
